# Define a test targets. Needs to list everything the tests depend on.

python_tests(
  name='test_a',
  dependencies=[
    'src/python/detailed:a_class',
  ],
  sources=globs('test_a.py'),
)

python_tests(
  name='test_b',
  dependencies=[
    'src/python/detailed:b_class',
  ],
  sources=globs('test_b.py'),
)

python_tests(
  name='test_c',
  dependencies=[
    'src/python/detailed:c_class',
  ],
  sources=globs('test_c.py'),
)
